### ISSUE TITLE
uploaded a file with long title it got overlapped with the image

### ISSUE THREAD

**Issue by snehaajency** [ajency/ajency-hiring#10]
![image](https://user-images.githubusercontent.com/4660706/144417078-ab1ab741-5ef1-4ea6-bb27-665ab48c10cd.png)

**Comment by snehaajency** [comment]
@MamataNivajekar issue is replicating

**Comment by MamataNivajekar** [comment]
@snehaajency  couldn't replicate
![image](https://user-images.githubusercontent.com/81617777/144439770-aed1ea45-effb-41f0-8baa-0da7f7ed43cc.png)
