### ISSUE TITLE
Captcha goes missing after you submit one response

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/ajency-hiring#13]
Problem: We fill up a form, and then when we want to fill next form an error is thrown.

Steps:
1. submit a form successfully.
2. green success toast comes
3. now fill up the form again, u get this msg

Suggestion or Goal:
Can we not refresh the pageso people can still send ?

![image](https://user-images.githubusercontent.com/55691499/144422050-21c56907-4f38-479c-8794-82e887932faa.png)

**Comment by MamataNivajekar** [comment]
@HazelColaco19  couldn't replicate

**Comment by HazelColaco19** [comment]
Could not replicate on my side either
