### ISSUE TITLE
contact us form  > font weight and color issue 

### ISSUE THREAD

**Issue by snehaajency** [ajency/ajency-hiring#2]
**case:**
 1. the marked links need to be blue.
2. font-family and font-weight is not matching with design.currently it is 700
 

issue:
![image](https://user-images.githubusercontent.com/4660706/144359876-993ba6b9-a2cf-4bbc-a77f-28162bc8d9b7.png)

design:
![image](https://user-images.githubusercontent.com/4660706/144359966-b20b3edb-e853-49f4-8b71-5b10e2a94be0.png)

**Comment by MamataNivajekar** [comment]
2. font weight & font size issue --> fixed

**Comment by snehaajency** [comment]
@MamataNivajekar font weight in design is 400

**Comment by MamataNivajekar** [comment]
> @MamataNivajekar font weight in design is 400

@snehaajency  400 font-weight looks too thin/light for "work sans" font-family
